package com.ldx.domain.export;

public class box {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column box.fba_id
     *
     * @mbg.generated
     */
    private String fbaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column box.invoice_id
     *
     * @mbg.generated
     */
    private String invoiceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column box.outside_id
     *
     * @mbg.generated
     */
    private String outsideId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column box.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column box.inhome_weight
     *
     * @mbg.generated
     */
    private String inhomeWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column box.inhome_x
     *
     * @mbg.generated
     */
    private String inhomeX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column box.inhome_y
     *
     * @mbg.generated
     */
    private String inhomeY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column box.inhome_z
     *
     * @mbg.generated
     */
    private String inhomeZ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column box.outhome_weight
     *
     * @mbg.generated
     */
    private String outhomeWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column box.outhome_x
     *
     * @mbg.generated
     */
    private String outhomeX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column box.outhome_y
     *
     * @mbg.generated
     */
    private String outhomeY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column box.outhome_z
     *
     * @mbg.generated
     */
    private String outhomeZ;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.fba_id
     *
     * @return the value of box.fba_id
     *
     * @mbg.generated
     */
    public String getFbaId() {
        return fbaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.fba_id
     *
     * @param fbaId the value for box.fba_id
     *
     * @mbg.generated
     */
    public void setFbaId(String fbaId) {
        this.fbaId = fbaId == null ? null : fbaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.invoice_id
     *
     * @return the value of box.invoice_id
     *
     * @mbg.generated
     */
    public String getInvoiceId() {
        return invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.invoice_id
     *
     * @param invoiceId the value for box.invoice_id
     *
     * @mbg.generated
     */
    public void setInvoiceId(String invoiceId) {
        this.invoiceId = invoiceId == null ? null : invoiceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.outside_id
     *
     * @return the value of box.outside_id
     *
     * @mbg.generated
     */
    public String getOutsideId() {
        return outsideId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.outside_id
     *
     * @param outsideId the value for box.outside_id
     *
     * @mbg.generated
     */
    public void setOutsideId(String outsideId) {
        this.outsideId = outsideId == null ? null : outsideId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.remark
     *
     * @return the value of box.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.remark
     *
     * @param remark the value for box.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.inhome_weight
     *
     * @return the value of box.inhome_weight
     *
     * @mbg.generated
     */
    public String getInhomeWeight() {
        return inhomeWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.inhome_weight
     *
     * @param inhomeWeight the value for box.inhome_weight
     *
     * @mbg.generated
     */
    public void setInhomeWeight(String inhomeWeight) {
        this.inhomeWeight = inhomeWeight == null ? null : inhomeWeight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.inhome_x
     *
     * @return the value of box.inhome_x
     *
     * @mbg.generated
     */
    public String getInhomeX() {
        return inhomeX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.inhome_x
     *
     * @param inhomeX the value for box.inhome_x
     *
     * @mbg.generated
     */
    public void setInhomeX(String inhomeX) {
        this.inhomeX = inhomeX == null ? null : inhomeX.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.inhome_y
     *
     * @return the value of box.inhome_y
     *
     * @mbg.generated
     */
    public String getInhomeY() {
        return inhomeY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.inhome_y
     *
     * @param inhomeY the value for box.inhome_y
     *
     * @mbg.generated
     */
    public void setInhomeY(String inhomeY) {
        this.inhomeY = inhomeY == null ? null : inhomeY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.inhome_z
     *
     * @return the value of box.inhome_z
     *
     * @mbg.generated
     */
    public String getInhomeZ() {
        return inhomeZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.inhome_z
     *
     * @param inhomeZ the value for box.inhome_z
     *
     * @mbg.generated
     */
    public void setInhomeZ(String inhomeZ) {
        this.inhomeZ = inhomeZ == null ? null : inhomeZ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.outhome_weight
     *
     * @return the value of box.outhome_weight
     *
     * @mbg.generated
     */
    public String getOuthomeWeight() {
        return outhomeWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.outhome_weight
     *
     * @param outhomeWeight the value for box.outhome_weight
     *
     * @mbg.generated
     */
    public void setOuthomeWeight(String outhomeWeight) {
        this.outhomeWeight = outhomeWeight == null ? null : outhomeWeight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.outhome_x
     *
     * @return the value of box.outhome_x
     *
     * @mbg.generated
     */
    public String getOuthomeX() {
        return outhomeX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.outhome_x
     *
     * @param outhomeX the value for box.outhome_x
     *
     * @mbg.generated
     */
    public void setOuthomeX(String outhomeX) {
        this.outhomeX = outhomeX == null ? null : outhomeX.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.outhome_y
     *
     * @return the value of box.outhome_y
     *
     * @mbg.generated
     */
    public String getOuthomeY() {
        return outhomeY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.outhome_y
     *
     * @param outhomeY the value for box.outhome_y
     *
     * @mbg.generated
     */
    public void setOuthomeY(String outhomeY) {
        this.outhomeY = outhomeY == null ? null : outhomeY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.outhome_z
     *
     * @return the value of box.outhome_z
     *
     * @mbg.generated
     */
    public String getOuthomeZ() {
        return outhomeZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.outhome_z
     *
     * @param outhomeZ the value for box.outhome_z
     *
     * @mbg.generated
     */
    public void setOuthomeZ(String outhomeZ) {
        this.outhomeZ = outhomeZ == null ? null : outhomeZ.trim();
    }
}