package com.ldx.domain.export;

import java.util.ArrayList;
import java.util.List;

public class boxExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table box
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table box
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table box
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    public boxExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table box
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFbaIdIsNull() {
            addCriterion("fba_id is null");
            return (Criteria) this;
        }

        public Criteria andFbaIdIsNotNull() {
            addCriterion("fba_id is not null");
            return (Criteria) this;
        }

        public Criteria andFbaIdEqualTo(String value) {
            addCriterion("fba_id =", value, "fbaId");
            return (Criteria) this;
        }

        public Criteria andFbaIdNotEqualTo(String value) {
            addCriterion("fba_id <>", value, "fbaId");
            return (Criteria) this;
        }

        public Criteria andFbaIdGreaterThan(String value) {
            addCriterion("fba_id >", value, "fbaId");
            return (Criteria) this;
        }

        public Criteria andFbaIdGreaterThanOrEqualTo(String value) {
            addCriterion("fba_id >=", value, "fbaId");
            return (Criteria) this;
        }

        public Criteria andFbaIdLessThan(String value) {
            addCriterion("fba_id <", value, "fbaId");
            return (Criteria) this;
        }

        public Criteria andFbaIdLessThanOrEqualTo(String value) {
            addCriterion("fba_id <=", value, "fbaId");
            return (Criteria) this;
        }

        public Criteria andFbaIdLike(String value) {
            addCriterion("fba_id like", value, "fbaId");
            return (Criteria) this;
        }

        public Criteria andFbaIdNotLike(String value) {
            addCriterion("fba_id not like", value, "fbaId");
            return (Criteria) this;
        }

        public Criteria andFbaIdIn(List<String> values) {
            addCriterion("fba_id in", values, "fbaId");
            return (Criteria) this;
        }

        public Criteria andFbaIdNotIn(List<String> values) {
            addCriterion("fba_id not in", values, "fbaId");
            return (Criteria) this;
        }

        public Criteria andFbaIdBetween(String value1, String value2) {
            addCriterion("fba_id between", value1, value2, "fbaId");
            return (Criteria) this;
        }

        public Criteria andFbaIdNotBetween(String value1, String value2) {
            addCriterion("fba_id not between", value1, value2, "fbaId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdIsNull() {
            addCriterion("invoice_id is null");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdIsNotNull() {
            addCriterion("invoice_id is not null");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdEqualTo(String value) {
            addCriterion("invoice_id =", value, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdNotEqualTo(String value) {
            addCriterion("invoice_id <>", value, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdGreaterThan(String value) {
            addCriterion("invoice_id >", value, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdGreaterThanOrEqualTo(String value) {
            addCriterion("invoice_id >=", value, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdLessThan(String value) {
            addCriterion("invoice_id <", value, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdLessThanOrEqualTo(String value) {
            addCriterion("invoice_id <=", value, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdLike(String value) {
            addCriterion("invoice_id like", value, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdNotLike(String value) {
            addCriterion("invoice_id not like", value, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdIn(List<String> values) {
            addCriterion("invoice_id in", values, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdNotIn(List<String> values) {
            addCriterion("invoice_id not in", values, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdBetween(String value1, String value2) {
            addCriterion("invoice_id between", value1, value2, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdNotBetween(String value1, String value2) {
            addCriterion("invoice_id not between", value1, value2, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andOutsideIdIsNull() {
            addCriterion("outside_id is null");
            return (Criteria) this;
        }

        public Criteria andOutsideIdIsNotNull() {
            addCriterion("outside_id is not null");
            return (Criteria) this;
        }

        public Criteria andOutsideIdEqualTo(String value) {
            addCriterion("outside_id =", value, "outsideId");
            return (Criteria) this;
        }

        public Criteria andOutsideIdNotEqualTo(String value) {
            addCriterion("outside_id <>", value, "outsideId");
            return (Criteria) this;
        }

        public Criteria andOutsideIdGreaterThan(String value) {
            addCriterion("outside_id >", value, "outsideId");
            return (Criteria) this;
        }

        public Criteria andOutsideIdGreaterThanOrEqualTo(String value) {
            addCriterion("outside_id >=", value, "outsideId");
            return (Criteria) this;
        }

        public Criteria andOutsideIdLessThan(String value) {
            addCriterion("outside_id <", value, "outsideId");
            return (Criteria) this;
        }

        public Criteria andOutsideIdLessThanOrEqualTo(String value) {
            addCriterion("outside_id <=", value, "outsideId");
            return (Criteria) this;
        }

        public Criteria andOutsideIdLike(String value) {
            addCriterion("outside_id like", value, "outsideId");
            return (Criteria) this;
        }

        public Criteria andOutsideIdNotLike(String value) {
            addCriterion("outside_id not like", value, "outsideId");
            return (Criteria) this;
        }

        public Criteria andOutsideIdIn(List<String> values) {
            addCriterion("outside_id in", values, "outsideId");
            return (Criteria) this;
        }

        public Criteria andOutsideIdNotIn(List<String> values) {
            addCriterion("outside_id not in", values, "outsideId");
            return (Criteria) this;
        }

        public Criteria andOutsideIdBetween(String value1, String value2) {
            addCriterion("outside_id between", value1, value2, "outsideId");
            return (Criteria) this;
        }

        public Criteria andOutsideIdNotBetween(String value1, String value2) {
            addCriterion("outside_id not between", value1, value2, "outsideId");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andInhomeWeightIsNull() {
            addCriterion("inhome_weight is null");
            return (Criteria) this;
        }

        public Criteria andInhomeWeightIsNotNull() {
            addCriterion("inhome_weight is not null");
            return (Criteria) this;
        }

        public Criteria andInhomeWeightEqualTo(String value) {
            addCriterion("inhome_weight =", value, "inhomeWeight");
            return (Criteria) this;
        }

        public Criteria andInhomeWeightNotEqualTo(String value) {
            addCriterion("inhome_weight <>", value, "inhomeWeight");
            return (Criteria) this;
        }

        public Criteria andInhomeWeightGreaterThan(String value) {
            addCriterion("inhome_weight >", value, "inhomeWeight");
            return (Criteria) this;
        }

        public Criteria andInhomeWeightGreaterThanOrEqualTo(String value) {
            addCriterion("inhome_weight >=", value, "inhomeWeight");
            return (Criteria) this;
        }

        public Criteria andInhomeWeightLessThan(String value) {
            addCriterion("inhome_weight <", value, "inhomeWeight");
            return (Criteria) this;
        }

        public Criteria andInhomeWeightLessThanOrEqualTo(String value) {
            addCriterion("inhome_weight <=", value, "inhomeWeight");
            return (Criteria) this;
        }

        public Criteria andInhomeWeightLike(String value) {
            addCriterion("inhome_weight like", value, "inhomeWeight");
            return (Criteria) this;
        }

        public Criteria andInhomeWeightNotLike(String value) {
            addCriterion("inhome_weight not like", value, "inhomeWeight");
            return (Criteria) this;
        }

        public Criteria andInhomeWeightIn(List<String> values) {
            addCriterion("inhome_weight in", values, "inhomeWeight");
            return (Criteria) this;
        }

        public Criteria andInhomeWeightNotIn(List<String> values) {
            addCriterion("inhome_weight not in", values, "inhomeWeight");
            return (Criteria) this;
        }

        public Criteria andInhomeWeightBetween(String value1, String value2) {
            addCriterion("inhome_weight between", value1, value2, "inhomeWeight");
            return (Criteria) this;
        }

        public Criteria andInhomeWeightNotBetween(String value1, String value2) {
            addCriterion("inhome_weight not between", value1, value2, "inhomeWeight");
            return (Criteria) this;
        }

        public Criteria andInhomeXIsNull() {
            addCriterion("inhome_x is null");
            return (Criteria) this;
        }

        public Criteria andInhomeXIsNotNull() {
            addCriterion("inhome_x is not null");
            return (Criteria) this;
        }

        public Criteria andInhomeXEqualTo(String value) {
            addCriterion("inhome_x =", value, "inhomeX");
            return (Criteria) this;
        }

        public Criteria andInhomeXNotEqualTo(String value) {
            addCriterion("inhome_x <>", value, "inhomeX");
            return (Criteria) this;
        }

        public Criteria andInhomeXGreaterThan(String value) {
            addCriterion("inhome_x >", value, "inhomeX");
            return (Criteria) this;
        }

        public Criteria andInhomeXGreaterThanOrEqualTo(String value) {
            addCriterion("inhome_x >=", value, "inhomeX");
            return (Criteria) this;
        }

        public Criteria andInhomeXLessThan(String value) {
            addCriterion("inhome_x <", value, "inhomeX");
            return (Criteria) this;
        }

        public Criteria andInhomeXLessThanOrEqualTo(String value) {
            addCriterion("inhome_x <=", value, "inhomeX");
            return (Criteria) this;
        }

        public Criteria andInhomeXLike(String value) {
            addCriterion("inhome_x like", value, "inhomeX");
            return (Criteria) this;
        }

        public Criteria andInhomeXNotLike(String value) {
            addCriterion("inhome_x not like", value, "inhomeX");
            return (Criteria) this;
        }

        public Criteria andInhomeXIn(List<String> values) {
            addCriterion("inhome_x in", values, "inhomeX");
            return (Criteria) this;
        }

        public Criteria andInhomeXNotIn(List<String> values) {
            addCriterion("inhome_x not in", values, "inhomeX");
            return (Criteria) this;
        }

        public Criteria andInhomeXBetween(String value1, String value2) {
            addCriterion("inhome_x between", value1, value2, "inhomeX");
            return (Criteria) this;
        }

        public Criteria andInhomeXNotBetween(String value1, String value2) {
            addCriterion("inhome_x not between", value1, value2, "inhomeX");
            return (Criteria) this;
        }

        public Criteria andInhomeYIsNull() {
            addCriterion("inhome_y is null");
            return (Criteria) this;
        }

        public Criteria andInhomeYIsNotNull() {
            addCriterion("inhome_y is not null");
            return (Criteria) this;
        }

        public Criteria andInhomeYEqualTo(String value) {
            addCriterion("inhome_y =", value, "inhomeY");
            return (Criteria) this;
        }

        public Criteria andInhomeYNotEqualTo(String value) {
            addCriterion("inhome_y <>", value, "inhomeY");
            return (Criteria) this;
        }

        public Criteria andInhomeYGreaterThan(String value) {
            addCriterion("inhome_y >", value, "inhomeY");
            return (Criteria) this;
        }

        public Criteria andInhomeYGreaterThanOrEqualTo(String value) {
            addCriterion("inhome_y >=", value, "inhomeY");
            return (Criteria) this;
        }

        public Criteria andInhomeYLessThan(String value) {
            addCriterion("inhome_y <", value, "inhomeY");
            return (Criteria) this;
        }

        public Criteria andInhomeYLessThanOrEqualTo(String value) {
            addCriterion("inhome_y <=", value, "inhomeY");
            return (Criteria) this;
        }

        public Criteria andInhomeYLike(String value) {
            addCriterion("inhome_y like", value, "inhomeY");
            return (Criteria) this;
        }

        public Criteria andInhomeYNotLike(String value) {
            addCriterion("inhome_y not like", value, "inhomeY");
            return (Criteria) this;
        }

        public Criteria andInhomeYIn(List<String> values) {
            addCriterion("inhome_y in", values, "inhomeY");
            return (Criteria) this;
        }

        public Criteria andInhomeYNotIn(List<String> values) {
            addCriterion("inhome_y not in", values, "inhomeY");
            return (Criteria) this;
        }

        public Criteria andInhomeYBetween(String value1, String value2) {
            addCriterion("inhome_y between", value1, value2, "inhomeY");
            return (Criteria) this;
        }

        public Criteria andInhomeYNotBetween(String value1, String value2) {
            addCriterion("inhome_y not between", value1, value2, "inhomeY");
            return (Criteria) this;
        }

        public Criteria andInhomeZIsNull() {
            addCriterion("inhome_z is null");
            return (Criteria) this;
        }

        public Criteria andInhomeZIsNotNull() {
            addCriterion("inhome_z is not null");
            return (Criteria) this;
        }

        public Criteria andInhomeZEqualTo(String value) {
            addCriterion("inhome_z =", value, "inhomeZ");
            return (Criteria) this;
        }

        public Criteria andInhomeZNotEqualTo(String value) {
            addCriterion("inhome_z <>", value, "inhomeZ");
            return (Criteria) this;
        }

        public Criteria andInhomeZGreaterThan(String value) {
            addCriterion("inhome_z >", value, "inhomeZ");
            return (Criteria) this;
        }

        public Criteria andInhomeZGreaterThanOrEqualTo(String value) {
            addCriterion("inhome_z >=", value, "inhomeZ");
            return (Criteria) this;
        }

        public Criteria andInhomeZLessThan(String value) {
            addCriterion("inhome_z <", value, "inhomeZ");
            return (Criteria) this;
        }

        public Criteria andInhomeZLessThanOrEqualTo(String value) {
            addCriterion("inhome_z <=", value, "inhomeZ");
            return (Criteria) this;
        }

        public Criteria andInhomeZLike(String value) {
            addCriterion("inhome_z like", value, "inhomeZ");
            return (Criteria) this;
        }

        public Criteria andInhomeZNotLike(String value) {
            addCriterion("inhome_z not like", value, "inhomeZ");
            return (Criteria) this;
        }

        public Criteria andInhomeZIn(List<String> values) {
            addCriterion("inhome_z in", values, "inhomeZ");
            return (Criteria) this;
        }

        public Criteria andInhomeZNotIn(List<String> values) {
            addCriterion("inhome_z not in", values, "inhomeZ");
            return (Criteria) this;
        }

        public Criteria andInhomeZBetween(String value1, String value2) {
            addCriterion("inhome_z between", value1, value2, "inhomeZ");
            return (Criteria) this;
        }

        public Criteria andInhomeZNotBetween(String value1, String value2) {
            addCriterion("inhome_z not between", value1, value2, "inhomeZ");
            return (Criteria) this;
        }

        public Criteria andOuthomeWeightIsNull() {
            addCriterion("outhome_weight is null");
            return (Criteria) this;
        }

        public Criteria andOuthomeWeightIsNotNull() {
            addCriterion("outhome_weight is not null");
            return (Criteria) this;
        }

        public Criteria andOuthomeWeightEqualTo(String value) {
            addCriterion("outhome_weight =", value, "outhomeWeight");
            return (Criteria) this;
        }

        public Criteria andOuthomeWeightNotEqualTo(String value) {
            addCriterion("outhome_weight <>", value, "outhomeWeight");
            return (Criteria) this;
        }

        public Criteria andOuthomeWeightGreaterThan(String value) {
            addCriterion("outhome_weight >", value, "outhomeWeight");
            return (Criteria) this;
        }

        public Criteria andOuthomeWeightGreaterThanOrEqualTo(String value) {
            addCriterion("outhome_weight >=", value, "outhomeWeight");
            return (Criteria) this;
        }

        public Criteria andOuthomeWeightLessThan(String value) {
            addCriterion("outhome_weight <", value, "outhomeWeight");
            return (Criteria) this;
        }

        public Criteria andOuthomeWeightLessThanOrEqualTo(String value) {
            addCriterion("outhome_weight <=", value, "outhomeWeight");
            return (Criteria) this;
        }

        public Criteria andOuthomeWeightLike(String value) {
            addCriterion("outhome_weight like", value, "outhomeWeight");
            return (Criteria) this;
        }

        public Criteria andOuthomeWeightNotLike(String value) {
            addCriterion("outhome_weight not like", value, "outhomeWeight");
            return (Criteria) this;
        }

        public Criteria andOuthomeWeightIn(List<String> values) {
            addCriterion("outhome_weight in", values, "outhomeWeight");
            return (Criteria) this;
        }

        public Criteria andOuthomeWeightNotIn(List<String> values) {
            addCriterion("outhome_weight not in", values, "outhomeWeight");
            return (Criteria) this;
        }

        public Criteria andOuthomeWeightBetween(String value1, String value2) {
            addCriterion("outhome_weight between", value1, value2, "outhomeWeight");
            return (Criteria) this;
        }

        public Criteria andOuthomeWeightNotBetween(String value1, String value2) {
            addCriterion("outhome_weight not between", value1, value2, "outhomeWeight");
            return (Criteria) this;
        }

        public Criteria andOuthomeXIsNull() {
            addCriterion("outhome_x is null");
            return (Criteria) this;
        }

        public Criteria andOuthomeXIsNotNull() {
            addCriterion("outhome_x is not null");
            return (Criteria) this;
        }

        public Criteria andOuthomeXEqualTo(String value) {
            addCriterion("outhome_x =", value, "outhomeX");
            return (Criteria) this;
        }

        public Criteria andOuthomeXNotEqualTo(String value) {
            addCriterion("outhome_x <>", value, "outhomeX");
            return (Criteria) this;
        }

        public Criteria andOuthomeXGreaterThan(String value) {
            addCriterion("outhome_x >", value, "outhomeX");
            return (Criteria) this;
        }

        public Criteria andOuthomeXGreaterThanOrEqualTo(String value) {
            addCriterion("outhome_x >=", value, "outhomeX");
            return (Criteria) this;
        }

        public Criteria andOuthomeXLessThan(String value) {
            addCriterion("outhome_x <", value, "outhomeX");
            return (Criteria) this;
        }

        public Criteria andOuthomeXLessThanOrEqualTo(String value) {
            addCriterion("outhome_x <=", value, "outhomeX");
            return (Criteria) this;
        }

        public Criteria andOuthomeXLike(String value) {
            addCriterion("outhome_x like", value, "outhomeX");
            return (Criteria) this;
        }

        public Criteria andOuthomeXNotLike(String value) {
            addCriterion("outhome_x not like", value, "outhomeX");
            return (Criteria) this;
        }

        public Criteria andOuthomeXIn(List<String> values) {
            addCriterion("outhome_x in", values, "outhomeX");
            return (Criteria) this;
        }

        public Criteria andOuthomeXNotIn(List<String> values) {
            addCriterion("outhome_x not in", values, "outhomeX");
            return (Criteria) this;
        }

        public Criteria andOuthomeXBetween(String value1, String value2) {
            addCriterion("outhome_x between", value1, value2, "outhomeX");
            return (Criteria) this;
        }

        public Criteria andOuthomeXNotBetween(String value1, String value2) {
            addCriterion("outhome_x not between", value1, value2, "outhomeX");
            return (Criteria) this;
        }

        public Criteria andOuthomeYIsNull() {
            addCriterion("outhome_y is null");
            return (Criteria) this;
        }

        public Criteria andOuthomeYIsNotNull() {
            addCriterion("outhome_y is not null");
            return (Criteria) this;
        }

        public Criteria andOuthomeYEqualTo(String value) {
            addCriterion("outhome_y =", value, "outhomeY");
            return (Criteria) this;
        }

        public Criteria andOuthomeYNotEqualTo(String value) {
            addCriterion("outhome_y <>", value, "outhomeY");
            return (Criteria) this;
        }

        public Criteria andOuthomeYGreaterThan(String value) {
            addCriterion("outhome_y >", value, "outhomeY");
            return (Criteria) this;
        }

        public Criteria andOuthomeYGreaterThanOrEqualTo(String value) {
            addCriterion("outhome_y >=", value, "outhomeY");
            return (Criteria) this;
        }

        public Criteria andOuthomeYLessThan(String value) {
            addCriterion("outhome_y <", value, "outhomeY");
            return (Criteria) this;
        }

        public Criteria andOuthomeYLessThanOrEqualTo(String value) {
            addCriterion("outhome_y <=", value, "outhomeY");
            return (Criteria) this;
        }

        public Criteria andOuthomeYLike(String value) {
            addCriterion("outhome_y like", value, "outhomeY");
            return (Criteria) this;
        }

        public Criteria andOuthomeYNotLike(String value) {
            addCriterion("outhome_y not like", value, "outhomeY");
            return (Criteria) this;
        }

        public Criteria andOuthomeYIn(List<String> values) {
            addCriterion("outhome_y in", values, "outhomeY");
            return (Criteria) this;
        }

        public Criteria andOuthomeYNotIn(List<String> values) {
            addCriterion("outhome_y not in", values, "outhomeY");
            return (Criteria) this;
        }

        public Criteria andOuthomeYBetween(String value1, String value2) {
            addCriterion("outhome_y between", value1, value2, "outhomeY");
            return (Criteria) this;
        }

        public Criteria andOuthomeYNotBetween(String value1, String value2) {
            addCriterion("outhome_y not between", value1, value2, "outhomeY");
            return (Criteria) this;
        }

        public Criteria andOuthomeZIsNull() {
            addCriterion("outhome_z is null");
            return (Criteria) this;
        }

        public Criteria andOuthomeZIsNotNull() {
            addCriterion("outhome_z is not null");
            return (Criteria) this;
        }

        public Criteria andOuthomeZEqualTo(String value) {
            addCriterion("outhome_z =", value, "outhomeZ");
            return (Criteria) this;
        }

        public Criteria andOuthomeZNotEqualTo(String value) {
            addCriterion("outhome_z <>", value, "outhomeZ");
            return (Criteria) this;
        }

        public Criteria andOuthomeZGreaterThan(String value) {
            addCriterion("outhome_z >", value, "outhomeZ");
            return (Criteria) this;
        }

        public Criteria andOuthomeZGreaterThanOrEqualTo(String value) {
            addCriterion("outhome_z >=", value, "outhomeZ");
            return (Criteria) this;
        }

        public Criteria andOuthomeZLessThan(String value) {
            addCriterion("outhome_z <", value, "outhomeZ");
            return (Criteria) this;
        }

        public Criteria andOuthomeZLessThanOrEqualTo(String value) {
            addCriterion("outhome_z <=", value, "outhomeZ");
            return (Criteria) this;
        }

        public Criteria andOuthomeZLike(String value) {
            addCriterion("outhome_z like", value, "outhomeZ");
            return (Criteria) this;
        }

        public Criteria andOuthomeZNotLike(String value) {
            addCriterion("outhome_z not like", value, "outhomeZ");
            return (Criteria) this;
        }

        public Criteria andOuthomeZIn(List<String> values) {
            addCriterion("outhome_z in", values, "outhomeZ");
            return (Criteria) this;
        }

        public Criteria andOuthomeZNotIn(List<String> values) {
            addCriterion("outhome_z not in", values, "outhomeZ");
            return (Criteria) this;
        }

        public Criteria andOuthomeZBetween(String value1, String value2) {
            addCriterion("outhome_z between", value1, value2, "outhomeZ");
            return (Criteria) this;
        }

        public Criteria andOuthomeZNotBetween(String value1, String value2) {
            addCriterion("outhome_z not between", value1, value2, "outhomeZ");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table box
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table box
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}