package com.ldx.domain.export;

public class cargo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo.cargo_id
     *
     * @mbg.generated
     */
    private String cargoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo.fba_id
     *
     * @mbg.generated
     */
    private String fbaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo.cargo_name
     *
     * @mbg.generated
     */
    private String cargoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo.cargo_enname
     *
     * @mbg.generated
     */
    private String cargoEnname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo.EUR
     *
     * @mbg.generated
     */
    private String eur;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo.PCS
     *
     * @mbg.generated
     */
    private String pcs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo.material
     *
     * @mbg.generated
     */
    private String material;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo.purpose
     *
     * @mbg.generated
     */
    private String purpose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo.style
     *
     * @mbg.generated
     */
    private String style;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo.customs_id
     *
     * @mbg.generated
     */
    private String customsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo.picture
     *
     * @mbg.generated
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo.company_id
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo.cargo_id
     *
     * @return the value of cargo.cargo_id
     *
     * @mbg.generated
     */
    public String getCargoId() {
        return cargoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo.cargo_id
     *
     * @param cargoId the value for cargo.cargo_id
     *
     * @mbg.generated
     */
    public void setCargoId(String cargoId) {
        this.cargoId = cargoId == null ? null : cargoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo.fba_id
     *
     * @return the value of cargo.fba_id
     *
     * @mbg.generated
     */
    public String getFbaId() {
        return fbaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo.fba_id
     *
     * @param fbaId the value for cargo.fba_id
     *
     * @mbg.generated
     */
    public void setFbaId(String fbaId) {
        this.fbaId = fbaId == null ? null : fbaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo.cargo_name
     *
     * @return the value of cargo.cargo_name
     *
     * @mbg.generated
     */
    public String getCargoName() {
        return cargoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo.cargo_name
     *
     * @param cargoName the value for cargo.cargo_name
     *
     * @mbg.generated
     */
    public void setCargoName(String cargoName) {
        this.cargoName = cargoName == null ? null : cargoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo.cargo_enname
     *
     * @return the value of cargo.cargo_enname
     *
     * @mbg.generated
     */
    public String getCargoEnname() {
        return cargoEnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo.cargo_enname
     *
     * @param cargoEnname the value for cargo.cargo_enname
     *
     * @mbg.generated
     */
    public void setCargoEnname(String cargoEnname) {
        this.cargoEnname = cargoEnname == null ? null : cargoEnname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo.EUR
     *
     * @return the value of cargo.EUR
     *
     * @mbg.generated
     */
    public String getEur() {
        return eur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo.EUR
     *
     * @param eur the value for cargo.EUR
     *
     * @mbg.generated
     */
    public void setEur(String eur) {
        this.eur = eur == null ? null : eur.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo.PCS
     *
     * @return the value of cargo.PCS
     *
     * @mbg.generated
     */
    public String getPcs() {
        return pcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo.PCS
     *
     * @param pcs the value for cargo.PCS
     *
     * @mbg.generated
     */
    public void setPcs(String pcs) {
        this.pcs = pcs == null ? null : pcs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo.material
     *
     * @return the value of cargo.material
     *
     * @mbg.generated
     */
    public String getMaterial() {
        return material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo.material
     *
     * @param material the value for cargo.material
     *
     * @mbg.generated
     */
    public void setMaterial(String material) {
        this.material = material == null ? null : material.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo.purpose
     *
     * @return the value of cargo.purpose
     *
     * @mbg.generated
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo.purpose
     *
     * @param purpose the value for cargo.purpose
     *
     * @mbg.generated
     */
    public void setPurpose(String purpose) {
        this.purpose = purpose == null ? null : purpose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo.style
     *
     * @return the value of cargo.style
     *
     * @mbg.generated
     */
    public String getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo.style
     *
     * @param style the value for cargo.style
     *
     * @mbg.generated
     */
    public void setStyle(String style) {
        this.style = style == null ? null : style.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo.customs_id
     *
     * @return the value of cargo.customs_id
     *
     * @mbg.generated
     */
    public String getCustomsId() {
        return customsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo.customs_id
     *
     * @param customsId the value for cargo.customs_id
     *
     * @mbg.generated
     */
    public void setCustomsId(String customsId) {
        this.customsId = customsId == null ? null : customsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo.remark
     *
     * @return the value of cargo.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo.remark
     *
     * @param remark the value for cargo.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo.picture
     *
     * @return the value of cargo.picture
     *
     * @mbg.generated
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo.picture
     *
     * @param picture the value for cargo.picture
     *
     * @mbg.generated
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo.company_id
     *
     * @return the value of cargo.company_id
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo.company_id
     *
     * @param companyId the value for cargo.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }
}