package com.ldx.domain.export;

public class Company {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_id
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_name
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_phone
     *
     * @mbg.generated
     */
    private String companyPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_type
     *
     * @mbg.generated
     */
    private String companyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_adress
     *
     * @mbg.generated
     */
    private String companyAdress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_id
     *
     * @return the value of company.company_id
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_id
     *
     * @param companyId the value for company.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_name
     *
     * @return the value of company.company_name
     *
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_name
     *
     * @param companyName the value for company.company_name
     *
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_phone
     *
     * @return the value of company.company_phone
     *
     * @mbg.generated
     */
    public String getCompanyPhone() {
        return companyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_phone
     *
     * @param companyPhone the value for company.company_phone
     *
     * @mbg.generated
     */
    public void setCompanyPhone(String companyPhone) {
        this.companyPhone = companyPhone == null ? null : companyPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_type
     *
     * @return the value of company.company_type
     *
     * @mbg.generated
     */
    public String getCompanyType() {
        return companyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_type
     *
     * @param companyType the value for company.company_type
     *
     * @mbg.generated
     */
    public void setCompanyType(String companyType) {
        this.companyType = companyType == null ? null : companyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_adress
     *
     * @return the value of company.company_adress
     *
     * @mbg.generated
     */
    public String getCompanyAdress() {
        return companyAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_adress
     *
     * @param companyAdress the value for company.company_adress
     *
     * @mbg.generated
     */
    public void setCompanyAdress(String companyAdress) {
        this.companyAdress = companyAdress == null ? null : companyAdress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.remark
     *
     * @return the value of company.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.remark
     *
     * @param remark the value for company.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.email
     *
     * @return the value of company.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    @Override
    public String toString() {
        return "Company{" +
                "companyId='" + companyId + '\'' +
                ", companyName='" + companyName + '\'' +
                ", companyPhone='" + companyPhone + '\'' +
                ", companyType='" + companyType + '\'' +
                ", companyAdress='" + companyAdress + '\'' +
                ", remark='" + remark + '\'' +
                ", email='" + email + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.email
     *
     * @param email the value for company.email
     *
     * @mbg.generated
     */

    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}