package com.ldx.domain.export;

import java.util.ArrayList;
import java.util.List;

public class invoiceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table invoice
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table invoice
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table invoice
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice
     *
     * @mbg.generated
     */
    public invoiceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table invoice
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInvoiceIdIsNull() {
            addCriterion("invoice_id is null");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdIsNotNull() {
            addCriterion("invoice_id is not null");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdEqualTo(String value) {
            addCriterion("invoice_id =", value, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdNotEqualTo(String value) {
            addCriterion("invoice_id <>", value, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdGreaterThan(String value) {
            addCriterion("invoice_id >", value, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdGreaterThanOrEqualTo(String value) {
            addCriterion("invoice_id >=", value, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdLessThan(String value) {
            addCriterion("invoice_id <", value, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdLessThanOrEqualTo(String value) {
            addCriterion("invoice_id <=", value, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdLike(String value) {
            addCriterion("invoice_id like", value, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdNotLike(String value) {
            addCriterion("invoice_id not like", value, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdIn(List<String> values) {
            addCriterion("invoice_id in", values, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdNotIn(List<String> values) {
            addCriterion("invoice_id not in", values, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdBetween(String value1, String value2) {
            addCriterion("invoice_id between", value1, value2, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdNotBetween(String value1, String value2) {
            addCriterion("invoice_id not between", value1, value2, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdIsNull() {
            addCriterion("service_id is null");
            return (Criteria) this;
        }

        public Criteria andServiceIdIsNotNull() {
            addCriterion("service_id is not null");
            return (Criteria) this;
        }

        public Criteria andServiceIdEqualTo(String value) {
            addCriterion("service_id =", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdNotEqualTo(String value) {
            addCriterion("service_id <>", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdGreaterThan(String value) {
            addCriterion("service_id >", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdGreaterThanOrEqualTo(String value) {
            addCriterion("service_id >=", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdLessThan(String value) {
            addCriterion("service_id <", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdLessThanOrEqualTo(String value) {
            addCriterion("service_id <=", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdLike(String value) {
            addCriterion("service_id like", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdNotLike(String value) {
            addCriterion("service_id not like", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdIn(List<String> values) {
            addCriterion("service_id in", values, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdNotIn(List<String> values) {
            addCriterion("service_id not in", values, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdBetween(String value1, String value2) {
            addCriterion("service_id between", value1, value2, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdNotBetween(String value1, String value2) {
            addCriterion("service_id not between", value1, value2, "serviceId");
            return (Criteria) this;
        }

        public Criteria andFbaIdIsNull() {
            addCriterion("fba_id is null");
            return (Criteria) this;
        }

        public Criteria andFbaIdIsNotNull() {
            addCriterion("fba_id is not null");
            return (Criteria) this;
        }

        public Criteria andFbaIdEqualTo(String value) {
            addCriterion("fba_id =", value, "fbaId");
            return (Criteria) this;
        }

        public Criteria andFbaIdNotEqualTo(String value) {
            addCriterion("fba_id <>", value, "fbaId");
            return (Criteria) this;
        }

        public Criteria andFbaIdGreaterThan(String value) {
            addCriterion("fba_id >", value, "fbaId");
            return (Criteria) this;
        }

        public Criteria andFbaIdGreaterThanOrEqualTo(String value) {
            addCriterion("fba_id >=", value, "fbaId");
            return (Criteria) this;
        }

        public Criteria andFbaIdLessThan(String value) {
            addCriterion("fba_id <", value, "fbaId");
            return (Criteria) this;
        }

        public Criteria andFbaIdLessThanOrEqualTo(String value) {
            addCriterion("fba_id <=", value, "fbaId");
            return (Criteria) this;
        }

        public Criteria andFbaIdLike(String value) {
            addCriterion("fba_id like", value, "fbaId");
            return (Criteria) this;
        }

        public Criteria andFbaIdNotLike(String value) {
            addCriterion("fba_id not like", value, "fbaId");
            return (Criteria) this;
        }

        public Criteria andFbaIdIn(List<String> values) {
            addCriterion("fba_id in", values, "fbaId");
            return (Criteria) this;
        }

        public Criteria andFbaIdNotIn(List<String> values) {
            addCriterion("fba_id not in", values, "fbaId");
            return (Criteria) this;
        }

        public Criteria andFbaIdBetween(String value1, String value2) {
            addCriterion("fba_id between", value1, value2, "fbaId");
            return (Criteria) this;
        }

        public Criteria andFbaIdNotBetween(String value1, String value2) {
            addCriterion("fba_id not between", value1, value2, "fbaId");
            return (Criteria) this;
        }

        public Criteria andInvoiceRemarkIsNull() {
            addCriterion("invoice_remark is null");
            return (Criteria) this;
        }

        public Criteria andInvoiceRemarkIsNotNull() {
            addCriterion("invoice_remark is not null");
            return (Criteria) this;
        }

        public Criteria andInvoiceRemarkEqualTo(String value) {
            addCriterion("invoice_remark =", value, "invoiceRemark");
            return (Criteria) this;
        }

        public Criteria andInvoiceRemarkNotEqualTo(String value) {
            addCriterion("invoice_remark <>", value, "invoiceRemark");
            return (Criteria) this;
        }

        public Criteria andInvoiceRemarkGreaterThan(String value) {
            addCriterion("invoice_remark >", value, "invoiceRemark");
            return (Criteria) this;
        }

        public Criteria andInvoiceRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("invoice_remark >=", value, "invoiceRemark");
            return (Criteria) this;
        }

        public Criteria andInvoiceRemarkLessThan(String value) {
            addCriterion("invoice_remark <", value, "invoiceRemark");
            return (Criteria) this;
        }

        public Criteria andInvoiceRemarkLessThanOrEqualTo(String value) {
            addCriterion("invoice_remark <=", value, "invoiceRemark");
            return (Criteria) this;
        }

        public Criteria andInvoiceRemarkLike(String value) {
            addCriterion("invoice_remark like", value, "invoiceRemark");
            return (Criteria) this;
        }

        public Criteria andInvoiceRemarkNotLike(String value) {
            addCriterion("invoice_remark not like", value, "invoiceRemark");
            return (Criteria) this;
        }

        public Criteria andInvoiceRemarkIn(List<String> values) {
            addCriterion("invoice_remark in", values, "invoiceRemark");
            return (Criteria) this;
        }

        public Criteria andInvoiceRemarkNotIn(List<String> values) {
            addCriterion("invoice_remark not in", values, "invoiceRemark");
            return (Criteria) this;
        }

        public Criteria andInvoiceRemarkBetween(String value1, String value2) {
            addCriterion("invoice_remark between", value1, value2, "invoiceRemark");
            return (Criteria) this;
        }

        public Criteria andInvoiceRemarkNotBetween(String value1, String value2) {
            addCriterion("invoice_remark not between", value1, value2, "invoiceRemark");
            return (Criteria) this;
        }

        public Criteria andInvoiceFromCompanyIsNull() {
            addCriterion("invoice_from_company is null");
            return (Criteria) this;
        }

        public Criteria andInvoiceFromCompanyIsNotNull() {
            addCriterion("invoice_from_company is not null");
            return (Criteria) this;
        }

        public Criteria andInvoiceFromCompanyEqualTo(String value) {
            addCriterion("invoice_from_company =", value, "invoiceFromCompany");
            return (Criteria) this;
        }

        public Criteria andInvoiceFromCompanyNotEqualTo(String value) {
            addCriterion("invoice_from_company <>", value, "invoiceFromCompany");
            return (Criteria) this;
        }

        public Criteria andInvoiceFromCompanyGreaterThan(String value) {
            addCriterion("invoice_from_company >", value, "invoiceFromCompany");
            return (Criteria) this;
        }

        public Criteria andInvoiceFromCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("invoice_from_company >=", value, "invoiceFromCompany");
            return (Criteria) this;
        }

        public Criteria andInvoiceFromCompanyLessThan(String value) {
            addCriterion("invoice_from_company <", value, "invoiceFromCompany");
            return (Criteria) this;
        }

        public Criteria andInvoiceFromCompanyLessThanOrEqualTo(String value) {
            addCriterion("invoice_from_company <=", value, "invoiceFromCompany");
            return (Criteria) this;
        }

        public Criteria andInvoiceFromCompanyLike(String value) {
            addCriterion("invoice_from_company like", value, "invoiceFromCompany");
            return (Criteria) this;
        }

        public Criteria andInvoiceFromCompanyNotLike(String value) {
            addCriterion("invoice_from_company not like", value, "invoiceFromCompany");
            return (Criteria) this;
        }

        public Criteria andInvoiceFromCompanyIn(List<String> values) {
            addCriterion("invoice_from_company in", values, "invoiceFromCompany");
            return (Criteria) this;
        }

        public Criteria andInvoiceFromCompanyNotIn(List<String> values) {
            addCriterion("invoice_from_company not in", values, "invoiceFromCompany");
            return (Criteria) this;
        }

        public Criteria andInvoiceFromCompanyBetween(String value1, String value2) {
            addCriterion("invoice_from_company between", value1, value2, "invoiceFromCompany");
            return (Criteria) this;
        }

        public Criteria andInvoiceFromCompanyNotBetween(String value1, String value2) {
            addCriterion("invoice_from_company not between", value1, value2, "invoiceFromCompany");
            return (Criteria) this;
        }

        public Criteria andToAdressIsNull() {
            addCriterion("to_adress is null");
            return (Criteria) this;
        }

        public Criteria andToAdressIsNotNull() {
            addCriterion("to_adress is not null");
            return (Criteria) this;
        }

        public Criteria andToAdressEqualTo(String value) {
            addCriterion("to_adress =", value, "toAdress");
            return (Criteria) this;
        }

        public Criteria andToAdressNotEqualTo(String value) {
            addCriterion("to_adress <>", value, "toAdress");
            return (Criteria) this;
        }

        public Criteria andToAdressGreaterThan(String value) {
            addCriterion("to_adress >", value, "toAdress");
            return (Criteria) this;
        }

        public Criteria andToAdressGreaterThanOrEqualTo(String value) {
            addCriterion("to_adress >=", value, "toAdress");
            return (Criteria) this;
        }

        public Criteria andToAdressLessThan(String value) {
            addCriterion("to_adress <", value, "toAdress");
            return (Criteria) this;
        }

        public Criteria andToAdressLessThanOrEqualTo(String value) {
            addCriterion("to_adress <=", value, "toAdress");
            return (Criteria) this;
        }

        public Criteria andToAdressLike(String value) {
            addCriterion("to_adress like", value, "toAdress");
            return (Criteria) this;
        }

        public Criteria andToAdressNotLike(String value) {
            addCriterion("to_adress not like", value, "toAdress");
            return (Criteria) this;
        }

        public Criteria andToAdressIn(List<String> values) {
            addCriterion("to_adress in", values, "toAdress");
            return (Criteria) this;
        }

        public Criteria andToAdressNotIn(List<String> values) {
            addCriterion("to_adress not in", values, "toAdress");
            return (Criteria) this;
        }

        public Criteria andToAdressBetween(String value1, String value2) {
            addCriterion("to_adress between", value1, value2, "toAdress");
            return (Criteria) this;
        }

        public Criteria andToAdressNotBetween(String value1, String value2) {
            addCriterion("to_adress not between", value1, value2, "toAdress");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andFromCompanyIsNull() {
            addCriterion("from_company is null");
            return (Criteria) this;
        }

        public Criteria andFromCompanyIsNotNull() {
            addCriterion("from_company is not null");
            return (Criteria) this;
        }

        public Criteria andFromCompanyEqualTo(String value) {
            addCriterion("from_company =", value, "fromCompany");
            return (Criteria) this;
        }

        public Criteria andFromCompanyNotEqualTo(String value) {
            addCriterion("from_company <>", value, "fromCompany");
            return (Criteria) this;
        }

        public Criteria andFromCompanyGreaterThan(String value) {
            addCriterion("from_company >", value, "fromCompany");
            return (Criteria) this;
        }

        public Criteria andFromCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("from_company >=", value, "fromCompany");
            return (Criteria) this;
        }

        public Criteria andFromCompanyLessThan(String value) {
            addCriterion("from_company <", value, "fromCompany");
            return (Criteria) this;
        }

        public Criteria andFromCompanyLessThanOrEqualTo(String value) {
            addCriterion("from_company <=", value, "fromCompany");
            return (Criteria) this;
        }

        public Criteria andFromCompanyLike(String value) {
            addCriterion("from_company like", value, "fromCompany");
            return (Criteria) this;
        }

        public Criteria andFromCompanyNotLike(String value) {
            addCriterion("from_company not like", value, "fromCompany");
            return (Criteria) this;
        }

        public Criteria andFromCompanyIn(List<String> values) {
            addCriterion("from_company in", values, "fromCompany");
            return (Criteria) this;
        }

        public Criteria andFromCompanyNotIn(List<String> values) {
            addCriterion("from_company not in", values, "fromCompany");
            return (Criteria) this;
        }

        public Criteria andFromCompanyBetween(String value1, String value2) {
            addCriterion("from_company between", value1, value2, "fromCompany");
            return (Criteria) this;
        }

        public Criteria andFromCompanyNotBetween(String value1, String value2) {
            addCriterion("from_company not between", value1, value2, "fromCompany");
            return (Criteria) this;
        }

        public Criteria andInhomeConweightIsNull() {
            addCriterion("inhome_conweight is null");
            return (Criteria) this;
        }

        public Criteria andInhomeConweightIsNotNull() {
            addCriterion("inhome_conweight is not null");
            return (Criteria) this;
        }

        public Criteria andInhomeConweightEqualTo(String value) {
            addCriterion("inhome_conweight =", value, "inhomeConweight");
            return (Criteria) this;
        }

        public Criteria andInhomeConweightNotEqualTo(String value) {
            addCriterion("inhome_conweight <>", value, "inhomeConweight");
            return (Criteria) this;
        }

        public Criteria andInhomeConweightGreaterThan(String value) {
            addCriterion("inhome_conweight >", value, "inhomeConweight");
            return (Criteria) this;
        }

        public Criteria andInhomeConweightGreaterThanOrEqualTo(String value) {
            addCriterion("inhome_conweight >=", value, "inhomeConweight");
            return (Criteria) this;
        }

        public Criteria andInhomeConweightLessThan(String value) {
            addCriterion("inhome_conweight <", value, "inhomeConweight");
            return (Criteria) this;
        }

        public Criteria andInhomeConweightLessThanOrEqualTo(String value) {
            addCriterion("inhome_conweight <=", value, "inhomeConweight");
            return (Criteria) this;
        }

        public Criteria andInhomeConweightLike(String value) {
            addCriterion("inhome_conweight like", value, "inhomeConweight");
            return (Criteria) this;
        }

        public Criteria andInhomeConweightNotLike(String value) {
            addCriterion("inhome_conweight not like", value, "inhomeConweight");
            return (Criteria) this;
        }

        public Criteria andInhomeConweightIn(List<String> values) {
            addCriterion("inhome_conweight in", values, "inhomeConweight");
            return (Criteria) this;
        }

        public Criteria andInhomeConweightNotIn(List<String> values) {
            addCriterion("inhome_conweight not in", values, "inhomeConweight");
            return (Criteria) this;
        }

        public Criteria andInhomeConweightBetween(String value1, String value2) {
            addCriterion("inhome_conweight between", value1, value2, "inhomeConweight");
            return (Criteria) this;
        }

        public Criteria andInhomeConweightNotBetween(String value1, String value2) {
            addCriterion("inhome_conweight not between", value1, value2, "inhomeConweight");
            return (Criteria) this;
        }

        public Criteria andInhomeConvol5IsNull() {
            addCriterion("inhome_convol5 is null");
            return (Criteria) this;
        }

        public Criteria andInhomeConvol5IsNotNull() {
            addCriterion("inhome_convol5 is not null");
            return (Criteria) this;
        }

        public Criteria andInhomeConvol5EqualTo(String value) {
            addCriterion("inhome_convol5 =", value, "inhomeConvol5");
            return (Criteria) this;
        }

        public Criteria andInhomeConvol5NotEqualTo(String value) {
            addCriterion("inhome_convol5 <>", value, "inhomeConvol5");
            return (Criteria) this;
        }

        public Criteria andInhomeConvol5GreaterThan(String value) {
            addCriterion("inhome_convol5 >", value, "inhomeConvol5");
            return (Criteria) this;
        }

        public Criteria andInhomeConvol5GreaterThanOrEqualTo(String value) {
            addCriterion("inhome_convol5 >=", value, "inhomeConvol5");
            return (Criteria) this;
        }

        public Criteria andInhomeConvol5LessThan(String value) {
            addCriterion("inhome_convol5 <", value, "inhomeConvol5");
            return (Criteria) this;
        }

        public Criteria andInhomeConvol5LessThanOrEqualTo(String value) {
            addCriterion("inhome_convol5 <=", value, "inhomeConvol5");
            return (Criteria) this;
        }

        public Criteria andInhomeConvol5Like(String value) {
            addCriterion("inhome_convol5 like", value, "inhomeConvol5");
            return (Criteria) this;
        }

        public Criteria andInhomeConvol5NotLike(String value) {
            addCriterion("inhome_convol5 not like", value, "inhomeConvol5");
            return (Criteria) this;
        }

        public Criteria andInhomeConvol5In(List<String> values) {
            addCriterion("inhome_convol5 in", values, "inhomeConvol5");
            return (Criteria) this;
        }

        public Criteria andInhomeConvol5NotIn(List<String> values) {
            addCriterion("inhome_convol5 not in", values, "inhomeConvol5");
            return (Criteria) this;
        }

        public Criteria andInhomeConvol5Between(String value1, String value2) {
            addCriterion("inhome_convol5 between", value1, value2, "inhomeConvol5");
            return (Criteria) this;
        }

        public Criteria andInhomeConvol5NotBetween(String value1, String value2) {
            addCriterion("inhome_convol5 not between", value1, value2, "inhomeConvol5");
            return (Criteria) this;
        }

        public Criteria andInhomeConvol6IsNull() {
            addCriterion("inhome_convol6 is null");
            return (Criteria) this;
        }

        public Criteria andInhomeConvol6IsNotNull() {
            addCriterion("inhome_convol6 is not null");
            return (Criteria) this;
        }

        public Criteria andInhomeConvol6EqualTo(String value) {
            addCriterion("inhome_convol6 =", value, "inhomeConvol6");
            return (Criteria) this;
        }

        public Criteria andInhomeConvol6NotEqualTo(String value) {
            addCriterion("inhome_convol6 <>", value, "inhomeConvol6");
            return (Criteria) this;
        }

        public Criteria andInhomeConvol6GreaterThan(String value) {
            addCriterion("inhome_convol6 >", value, "inhomeConvol6");
            return (Criteria) this;
        }

        public Criteria andInhomeConvol6GreaterThanOrEqualTo(String value) {
            addCriterion("inhome_convol6 >=", value, "inhomeConvol6");
            return (Criteria) this;
        }

        public Criteria andInhomeConvol6LessThan(String value) {
            addCriterion("inhome_convol6 <", value, "inhomeConvol6");
            return (Criteria) this;
        }

        public Criteria andInhomeConvol6LessThanOrEqualTo(String value) {
            addCriterion("inhome_convol6 <=", value, "inhomeConvol6");
            return (Criteria) this;
        }

        public Criteria andInhomeConvol6Like(String value) {
            addCriterion("inhome_convol6 like", value, "inhomeConvol6");
            return (Criteria) this;
        }

        public Criteria andInhomeConvol6NotLike(String value) {
            addCriterion("inhome_convol6 not like", value, "inhomeConvol6");
            return (Criteria) this;
        }

        public Criteria andInhomeConvol6In(List<String> values) {
            addCriterion("inhome_convol6 in", values, "inhomeConvol6");
            return (Criteria) this;
        }

        public Criteria andInhomeConvol6NotIn(List<String> values) {
            addCriterion("inhome_convol6 not in", values, "inhomeConvol6");
            return (Criteria) this;
        }

        public Criteria andInhomeConvol6Between(String value1, String value2) {
            addCriterion("inhome_convol6 between", value1, value2, "inhomeConvol6");
            return (Criteria) this;
        }

        public Criteria andInhomeConvol6NotBetween(String value1, String value2) {
            addCriterion("inhome_convol6 not between", value1, value2, "inhomeConvol6");
            return (Criteria) this;
        }

        public Criteria andQueryIdIsNull() {
            addCriterion("query_id is null");
            return (Criteria) this;
        }

        public Criteria andQueryIdIsNotNull() {
            addCriterion("query_id is not null");
            return (Criteria) this;
        }

        public Criteria andQueryIdEqualTo(String value) {
            addCriterion("query_id =", value, "queryId");
            return (Criteria) this;
        }

        public Criteria andQueryIdNotEqualTo(String value) {
            addCriterion("query_id <>", value, "queryId");
            return (Criteria) this;
        }

        public Criteria andQueryIdGreaterThan(String value) {
            addCriterion("query_id >", value, "queryId");
            return (Criteria) this;
        }

        public Criteria andQueryIdGreaterThanOrEqualTo(String value) {
            addCriterion("query_id >=", value, "queryId");
            return (Criteria) this;
        }

        public Criteria andQueryIdLessThan(String value) {
            addCriterion("query_id <", value, "queryId");
            return (Criteria) this;
        }

        public Criteria andQueryIdLessThanOrEqualTo(String value) {
            addCriterion("query_id <=", value, "queryId");
            return (Criteria) this;
        }

        public Criteria andQueryIdLike(String value) {
            addCriterion("query_id like", value, "queryId");
            return (Criteria) this;
        }

        public Criteria andQueryIdNotLike(String value) {
            addCriterion("query_id not like", value, "queryId");
            return (Criteria) this;
        }

        public Criteria andQueryIdIn(List<String> values) {
            addCriterion("query_id in", values, "queryId");
            return (Criteria) this;
        }

        public Criteria andQueryIdNotIn(List<String> values) {
            addCriterion("query_id not in", values, "queryId");
            return (Criteria) this;
        }

        public Criteria andQueryIdBetween(String value1, String value2) {
            addCriterion("query_id between", value1, value2, "queryId");
            return (Criteria) this;
        }

        public Criteria andQueryIdNotBetween(String value1, String value2) {
            addCriterion("query_id not between", value1, value2, "queryId");
            return (Criteria) this;
        }

        public Criteria andOuthomeConweight2IsNull() {
            addCriterion("outhome_conweight2 is null");
            return (Criteria) this;
        }

        public Criteria andOuthomeConweight2IsNotNull() {
            addCriterion("outhome_conweight2 is not null");
            return (Criteria) this;
        }

        public Criteria andOuthomeConweight2EqualTo(String value) {
            addCriterion("outhome_conweight2 =", value, "outhomeConweight2");
            return (Criteria) this;
        }

        public Criteria andOuthomeConweight2NotEqualTo(String value) {
            addCriterion("outhome_conweight2 <>", value, "outhomeConweight2");
            return (Criteria) this;
        }

        public Criteria andOuthomeConweight2GreaterThan(String value) {
            addCriterion("outhome_conweight2 >", value, "outhomeConweight2");
            return (Criteria) this;
        }

        public Criteria andOuthomeConweight2GreaterThanOrEqualTo(String value) {
            addCriterion("outhome_conweight2 >=", value, "outhomeConweight2");
            return (Criteria) this;
        }

        public Criteria andOuthomeConweight2LessThan(String value) {
            addCriterion("outhome_conweight2 <", value, "outhomeConweight2");
            return (Criteria) this;
        }

        public Criteria andOuthomeConweight2LessThanOrEqualTo(String value) {
            addCriterion("outhome_conweight2 <=", value, "outhomeConweight2");
            return (Criteria) this;
        }

        public Criteria andOuthomeConweight2Like(String value) {
            addCriterion("outhome_conweight2 like", value, "outhomeConweight2");
            return (Criteria) this;
        }

        public Criteria andOuthomeConweight2NotLike(String value) {
            addCriterion("outhome_conweight2 not like", value, "outhomeConweight2");
            return (Criteria) this;
        }

        public Criteria andOuthomeConweight2In(List<String> values) {
            addCriterion("outhome_conweight2 in", values, "outhomeConweight2");
            return (Criteria) this;
        }

        public Criteria andOuthomeConweight2NotIn(List<String> values) {
            addCriterion("outhome_conweight2 not in", values, "outhomeConweight2");
            return (Criteria) this;
        }

        public Criteria andOuthomeConweight2Between(String value1, String value2) {
            addCriterion("outhome_conweight2 between", value1, value2, "outhomeConweight2");
            return (Criteria) this;
        }

        public Criteria andOuthomeConweight2NotBetween(String value1, String value2) {
            addCriterion("outhome_conweight2 not between", value1, value2, "outhomeConweight2");
            return (Criteria) this;
        }

        public Criteria andOuthomeConvol5IsNull() {
            addCriterion("outhome_convol5 is null");
            return (Criteria) this;
        }

        public Criteria andOuthomeConvol5IsNotNull() {
            addCriterion("outhome_convol5 is not null");
            return (Criteria) this;
        }

        public Criteria andOuthomeConvol5EqualTo(String value) {
            addCriterion("outhome_convol5 =", value, "outhomeConvol5");
            return (Criteria) this;
        }

        public Criteria andOuthomeConvol5NotEqualTo(String value) {
            addCriterion("outhome_convol5 <>", value, "outhomeConvol5");
            return (Criteria) this;
        }

        public Criteria andOuthomeConvol5GreaterThan(String value) {
            addCriterion("outhome_convol5 >", value, "outhomeConvol5");
            return (Criteria) this;
        }

        public Criteria andOuthomeConvol5GreaterThanOrEqualTo(String value) {
            addCriterion("outhome_convol5 >=", value, "outhomeConvol5");
            return (Criteria) this;
        }

        public Criteria andOuthomeConvol5LessThan(String value) {
            addCriterion("outhome_convol5 <", value, "outhomeConvol5");
            return (Criteria) this;
        }

        public Criteria andOuthomeConvol5LessThanOrEqualTo(String value) {
            addCriterion("outhome_convol5 <=", value, "outhomeConvol5");
            return (Criteria) this;
        }

        public Criteria andOuthomeConvol5Like(String value) {
            addCriterion("outhome_convol5 like", value, "outhomeConvol5");
            return (Criteria) this;
        }

        public Criteria andOuthomeConvol5NotLike(String value) {
            addCriterion("outhome_convol5 not like", value, "outhomeConvol5");
            return (Criteria) this;
        }

        public Criteria andOuthomeConvol5In(List<String> values) {
            addCriterion("outhome_convol5 in", values, "outhomeConvol5");
            return (Criteria) this;
        }

        public Criteria andOuthomeConvol5NotIn(List<String> values) {
            addCriterion("outhome_convol5 not in", values, "outhomeConvol5");
            return (Criteria) this;
        }

        public Criteria andOuthomeConvol5Between(String value1, String value2) {
            addCriterion("outhome_convol5 between", value1, value2, "outhomeConvol5");
            return (Criteria) this;
        }

        public Criteria andOuthomeConvol5NotBetween(String value1, String value2) {
            addCriterion("outhome_convol5 not between", value1, value2, "outhomeConvol5");
            return (Criteria) this;
        }

        public Criteria andOuthomeConvol6IsNull() {
            addCriterion("outhome_convol6 is null");
            return (Criteria) this;
        }

        public Criteria andOuthomeConvol6IsNotNull() {
            addCriterion("outhome_convol6 is not null");
            return (Criteria) this;
        }

        public Criteria andOuthomeConvol6EqualTo(String value) {
            addCriterion("outhome_convol6 =", value, "outhomeConvol6");
            return (Criteria) this;
        }

        public Criteria andOuthomeConvol6NotEqualTo(String value) {
            addCriterion("outhome_convol6 <>", value, "outhomeConvol6");
            return (Criteria) this;
        }

        public Criteria andOuthomeConvol6GreaterThan(String value) {
            addCriterion("outhome_convol6 >", value, "outhomeConvol6");
            return (Criteria) this;
        }

        public Criteria andOuthomeConvol6GreaterThanOrEqualTo(String value) {
            addCriterion("outhome_convol6 >=", value, "outhomeConvol6");
            return (Criteria) this;
        }

        public Criteria andOuthomeConvol6LessThan(String value) {
            addCriterion("outhome_convol6 <", value, "outhomeConvol6");
            return (Criteria) this;
        }

        public Criteria andOuthomeConvol6LessThanOrEqualTo(String value) {
            addCriterion("outhome_convol6 <=", value, "outhomeConvol6");
            return (Criteria) this;
        }

        public Criteria andOuthomeConvol6Like(String value) {
            addCriterion("outhome_convol6 like", value, "outhomeConvol6");
            return (Criteria) this;
        }

        public Criteria andOuthomeConvol6NotLike(String value) {
            addCriterion("outhome_convol6 not like", value, "outhomeConvol6");
            return (Criteria) this;
        }

        public Criteria andOuthomeConvol6In(List<String> values) {
            addCriterion("outhome_convol6 in", values, "outhomeConvol6");
            return (Criteria) this;
        }

        public Criteria andOuthomeConvol6NotIn(List<String> values) {
            addCriterion("outhome_convol6 not in", values, "outhomeConvol6");
            return (Criteria) this;
        }

        public Criteria andOuthomeConvol6Between(String value1, String value2) {
            addCriterion("outhome_convol6 between", value1, value2, "outhomeConvol6");
            return (Criteria) this;
        }

        public Criteria andOuthomeConvol6NotBetween(String value1, String value2) {
            addCriterion("outhome_convol6 not between", value1, value2, "outhomeConvol6");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(String value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(String value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(String value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(String value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(String value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(String value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLike(String value) {
            addCriterion("price like", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotLike(String value) {
            addCriterion("price not like", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<String> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<String> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(String value1, String value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(String value1, String value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andCountryIsNull() {
            addCriterion("country is null");
            return (Criteria) this;
        }

        public Criteria andCountryIsNotNull() {
            addCriterion("country is not null");
            return (Criteria) this;
        }

        public Criteria andCountryEqualTo(String value) {
            addCriterion("country =", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotEqualTo(String value) {
            addCriterion("country <>", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThan(String value) {
            addCriterion("country >", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThanOrEqualTo(String value) {
            addCriterion("country >=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThan(String value) {
            addCriterion("country <", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThanOrEqualTo(String value) {
            addCriterion("country <=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLike(String value) {
            addCriterion("country like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotLike(String value) {
            addCriterion("country not like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryIn(List<String> values) {
            addCriterion("country in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotIn(List<String> values) {
            addCriterion("country not in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryBetween(String value1, String value2) {
            addCriterion("country between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotBetween(String value1, String value2) {
            addCriterion("country not between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andDateIsNull() {
            addCriterion("date is null");
            return (Criteria) this;
        }

        public Criteria andDateIsNotNull() {
            addCriterion("date is not null");
            return (Criteria) this;
        }

        public Criteria andDateEqualTo(String value) {
            addCriterion("date =", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotEqualTo(String value) {
            addCriterion("date <>", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThan(String value) {
            addCriterion("date >", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThanOrEqualTo(String value) {
            addCriterion("date >=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThan(String value) {
            addCriterion("date <", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThanOrEqualTo(String value) {
            addCriterion("date <=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLike(String value) {
            addCriterion("date like", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotLike(String value) {
            addCriterion("date not like", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateIn(List<String> values) {
            addCriterion("date in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotIn(List<String> values) {
            addCriterion("date not in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateBetween(String value1, String value2) {
            addCriterion("date between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotBetween(String value1, String value2) {
            addCriterion("date not between", value1, value2, "date");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table invoice
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table invoice
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}