package com.ldx.domain.export;

import java.util.Date;

public class invoice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.invoice_id
     *
     * @mbg.generated
     */
    private String invoiceId;

    private String linkTest;

    public String getLinkTest() {
        return linkTest;
    }

    public void setLinkTest(String linkTest) {
        this.linkTest = linkTest;
    }

    private String link;

    public String getLink() {
        return link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.service_id
     *
     * @mbg.generated
     */
    private String serviceId;

    private String serviceName;

    public String getServiceName() {
        return serviceName;
    }

    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.fba_id
     *
     * @mbg.generated
     */
    private String fbaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.invoice_remark
     *
     * @mbg.generated
     */
    private String invoiceRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.invoice_from_company
     *
     * @mbg.generated
     */
    private String invoiceFromCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.to_adress
     *
     * @mbg.generated
     */
    private String toAdress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.from_company
     *
     * @mbg.generated
     */
    private String fromCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.inhome_conweight
     *
     * @mbg.generated
     */
    private String inhomeConweight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.inhome_convol5
     *
     * @mbg.generated
     */
    private String inhomeConvol5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.inhome_convol6
     *
     * @mbg.generated
     */
    private String inhomeConvol6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.query_id
     *
     * @mbg.generated
     */
    private String queryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.outhome_conweight2
     *
     * @mbg.generated
     */
    private String outhomeConweight2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.outhome_convol5
     *
     * @mbg.generated
     */
    private String outhomeConvol5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.outhome_convol6
     *
     * @mbg.generated
     */
    private String outhomeConvol6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.price
     *
     * @mbg.generated
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.country
     *
     * @mbg.generated
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.invoice_id
     *
     * @return the value of invoice.invoice_id
     *
     * @mbg.generated
     */
    public String getInvoiceId() {
        return invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.invoice_id
     *
     * @param invoiceId the value for invoice.invoice_id
     *
     * @mbg.generated
     */
    public void setInvoiceId(String invoiceId) {
        this.invoiceId = invoiceId == null ? null : invoiceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.service_id
     *
     * @return the value of invoice.service_id
     *
     * @mbg.generated
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.service_id
     *
     * @param serviceId the value for invoice.service_id
     *
     * @mbg.generated
     */
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId == null ? null : serviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.fba_id
     *
     * @return the value of invoice.fba_id
     *
     * @mbg.generated
     */
    public String getFbaId() {
        return fbaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.fba_id
     *
     * @param fbaId the value for invoice.fba_id
     *
     * @mbg.generated
     */
    public void setFbaId(String fbaId) {
        this.fbaId = fbaId == null ? null : fbaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.invoice_remark
     *
     * @return the value of invoice.invoice_remark
     *
     * @mbg.generated
     */
    public String getInvoiceRemark() {
        return invoiceRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.invoice_remark
     *
     * @param invoiceRemark the value for invoice.invoice_remark
     *
     * @mbg.generated
     */
    public void setInvoiceRemark(String invoiceRemark) {
        this.invoiceRemark = invoiceRemark == null ? null : invoiceRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.invoice_from_company
     *
     * @return the value of invoice.invoice_from_company
     *
     * @mbg.generated
     */
    public String getInvoiceFromCompany() {
        return invoiceFromCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.invoice_from_company
     *
     * @param invoiceFromCompany the value for invoice.invoice_from_company
     *
     * @mbg.generated
     */
    public void setInvoiceFromCompany(String invoiceFromCompany) {
        this.invoiceFromCompany = invoiceFromCompany == null ? null : invoiceFromCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.to_adress
     *
     * @return the value of invoice.to_adress
     *
     * @mbg.generated
     */
    public String getToAdress() {
        return toAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.to_adress
     *
     * @param toAdress the value for invoice.to_adress
     *
     * @mbg.generated
     */
    public void setToAdress(String toAdress) {
        this.toAdress = toAdress == null ? null : toAdress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.remark
     *
     * @return the value of invoice.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.remark
     *
     * @param remark the value for invoice.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.from_company
     *
     * @return the value of invoice.from_company
     *
     * @mbg.generated
     */
    public String getFromCompany() {
        return fromCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.from_company
     *
     * @param fromCompany the value for invoice.from_company
     *
     * @mbg.generated
     */
    public void setFromCompany(String fromCompany) {
        this.fromCompany = fromCompany == null ? null : fromCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.inhome_conweight
     *
     * @return the value of invoice.inhome_conweight
     *
     * @mbg.generated
     */
    public String getInhomeConweight() {
        return inhomeConweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.inhome_conweight
     *
     * @param inhomeConweight the value for invoice.inhome_conweight
     *
     * @mbg.generated
     */
    public void setInhomeConweight(String inhomeConweight) {
        this.inhomeConweight = inhomeConweight == null ? null : inhomeConweight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.inhome_convol5
     *
     * @return the value of invoice.inhome_convol5
     *
     * @mbg.generated
     */
    public String getInhomeConvol5() {
        return inhomeConvol5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.inhome_convol5
     *
     * @param inhomeConvol5 the value for invoice.inhome_convol5
     *
     * @mbg.generated
     */
    public void setInhomeConvol5(String inhomeConvol5) {
        this.inhomeConvol5 = inhomeConvol5 == null ? null : inhomeConvol5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.inhome_convol6
     *
     * @return the value of invoice.inhome_convol6
     *
     * @mbg.generated
     */
    public String getInhomeConvol6() {
        return inhomeConvol6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.inhome_convol6
     *
     * @param inhomeConvol6 the value for invoice.inhome_convol6
     *
     * @mbg.generated
     */
    public void setInhomeConvol6(String inhomeConvol6) {
        this.inhomeConvol6 = inhomeConvol6 == null ? null : inhomeConvol6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.query_id
     *
     * @return the value of invoice.query_id
     *
     * @mbg.generated
     */
    public String getQueryId() {
        return queryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.query_id
     *
     * @param queryId the value for invoice.query_id
     *
     * @mbg.generated
     */
    public void setQueryId(String queryId) {
        this.queryId = queryId == null ? null : queryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.outhome_conweight2
     *
     * @return the value of invoice.outhome_conweight2
     *
     * @mbg.generated
     */
    public String getOuthomeConweight2() {
        return outhomeConweight2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.outhome_conweight2
     *
     * @param outhomeConweight2 the value for invoice.outhome_conweight2
     *
     * @mbg.generated
     */
    public void setOuthomeConweight2(String outhomeConweight2) {
        this.outhomeConweight2 = outhomeConweight2 == null ? null : outhomeConweight2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.outhome_convol5
     *
     * @return the value of invoice.outhome_convol5
     *
     * @mbg.generated
     */
    public String getOuthomeConvol5() {
        return outhomeConvol5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.outhome_convol5
     *
     * @param outhomeConvol5 the value for invoice.outhome_convol5
     *
     * @mbg.generated
     */
    public void setOuthomeConvol5(String outhomeConvol5) {
        this.outhomeConvol5 = outhomeConvol5 == null ? null : outhomeConvol5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.outhome_convol6
     *
     * @return the value of invoice.outhome_convol6
     *
     * @mbg.generated
     */
    public String getOuthomeConvol6() {
        return outhomeConvol6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.outhome_convol6
     *
     * @param outhomeConvol6 the value for invoice.outhome_convol6
     *
     * @mbg.generated
     */
    public void setOuthomeConvol6(String outhomeConvol6) {
        this.outhomeConvol6 = outhomeConvol6 == null ? null : outhomeConvol6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.user_id
     *
     * @return the value of invoice.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.user_id
     *
     * @param userId the value for invoice.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.price
     *
     * @return the value of invoice.price
     *
     * @mbg.generated
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.price
     *
     * @param price the value for invoice.price
     *
     * @mbg.generated
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.country
     *
     * @return the value of invoice.country
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.country
     *
     * @param country the value for invoice.country
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.date
     *
     * @return the value of invoice.date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.date
     *
     * @param date the value for invoice.date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date == null ? null : date;
    }
}