package com.ldx.dao.export;

import com.ldx.domain.export.box;
import com.ldx.domain.export.boxExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface boxDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    long countByExample(boxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    int deleteByExample(boxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String fbaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    int insert(box record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    int insertSelective(box record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    List<box> selectByExample(boxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    box selectByPrimaryKey(String fbaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") box record, @Param("example") boxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") box record, @Param("example") boxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(box record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(box record);
}