package com.ldx.dao.export;

import com.ldx.domain.export.cargo;
import com.ldx.domain.export.cargoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface cargoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated
     */
    long countByExample(cargoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated
     */
    int deleteByExample(cargoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String cargoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated
     */
    int insert(cargo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated
     */
    int insertSelective(cargo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated
     */
    List<cargo> selectByExample(cargoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated
     */
    cargo selectByPrimaryKey(String cargoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") cargo record, @Param("example") cargoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") cargo record, @Param("example") cargoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(cargo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(cargo record);
}